# Apply to all files without commiting:
# pre-commit run --all-files
# Update this file:
# pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black formatter
        args: [--line-length=120]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
